import type { CartFacts } from "./schema.ts";
import { getOffer, upgradeTarget } from "./catalog.ts";
import { milestone, TICKETS_PER_UPGRADE } from "./policy.ts";

/**
 * What the marketer actually sends.
 *
 * There is no CRM here and there won't be one this sprint, so the real output
 * of an approval isn't a database write — it's text a person can paste into
 * their email client on Monday morning. This file is that text.
 *
 * Deliberately templated rather than generated by a fourth agent. Copy is the
 * one artifact a fan reads word for word, which makes it the place where a
 * hallucination does the most damage and buys the least: a model might write a
 * warmer sentence, and it might also promise a fixture that isn't scheduled or
 * a discount we don't offer. Templates can't. The marketer edits before sending
 * anyway, so the upside of generating it is small and the downside isn't.
 *
 * The tone rule throughout: say the thing, don't perform enthusiasm. A club
 * this size is talking to people who may well have met the players.
 */

export interface SendCopy {
  subject: string;
  email: string;
  sms: string;
}

function seatPhrase(cart: CartFacts): string {
  return `${cart.seats} seat${cart.seats === 1 ? "" : "s"} in the ${cart.section}`;
}

/**
 * The milestone line, when this cart earns one.
 *
 * Goes in every template rather than only the reminder, because a fan crossing
 * their 45th ticket should hear about it whatever else we're sending. It also
 * turns the one message a loyal fan gets from a nag into news, which is the
 * whole point of having it.
 */
function milestoneLine(cart: CartFacts): string {
  const m = milestone(cart);
  if (!m) return "";
  const party =
    cart.seats === 1 ? "you" : cart.seats === 2 ? "both of you" : `all ${cart.seats} of you`;
  const lead = `\n\nAnd these take you to ${m.ticketsAfter} tickets with us. Every ${TICKETS_PER_UPGRADE} earns something back`;

  // Already in the best seats in the ground, so the thank-you is the price
  // rather than the seat. Same gesture, said plainly.
  if (m.reward.kind === "priced_down") {
    return `${lead}. You're already in the best seats in the ground, so there's nowhere to move you — instead, next time you buy, your ${cart.section} seats are yours at ${m.reward.section} prices.`;
  }
  return `${lead} — and it lands on the tickets already in your cart. Finish up and ${party} move to the ${m.reward.section} for this match, at the price you're paying now. You'll be sitting together.`;
}

export function buildCopy(cart: CartFacts, offerId: string): SendCopy {
  const offer = getOffer(offerId);
  const seats = seatPhrase(cart);
  const label = offer?.label ?? "your cart";

  switch (offerId) {
    case "reminder_only":
      return {
        subject: !milestone(cart)
          ? "Your Seawolves seats are still held"
          : milestone(cart)!.reward.kind === "upgrade"
            ? "These seats come with an upgrade"
            : "You're one order from a better price",
        email: `Hi,

You left ${seats} in your cart. They're still there if you want them — nothing has been taken off the board yet.${milestoneLine(cart)}

Finish up here: [CART LINK]

See you at the match,
Seattle Seawolves`,
        sms: (() => {
          const m = milestone(cart);
          if (!m) return `Your ${seats} for the Seawolves are still held. Finish up: [CART LINK]`;
          return m.reward.kind === "upgrade"
            ? `Your ${seats} are still held — and they take you past ${m.at} tickets, so we'll move the whole party up to the ${m.reward.section} on this order. Finish up: [CART LINK]`
            : `Your ${seats} are still held — and they take you past ${m.at} tickets, so your next order is ${cart.section} seats at ${m.reward.section} prices. Finish up: [CART LINK]`;
        })(),
      };

    case "discount_10":
    case "discount_15": {
      const pct = offerId === "discount_15" ? "15%" : "10%";
      const saved = offer ? offer.cashCost(cart).toFixed(2) : "0.00";
      return {
        subject: `${pct} off your Seawolves seats`,
        email: `Hi,

You left ${seats} in your cart. Here's ${pct} off — $${saved} — if you'd like to come and see us.

Finish up here: [CART LINK]

See you at the match,
Seattle Seawolves`,
        sms: `${pct} off your ${seats} for the Seawolves — $${saved} off. Finish up: [CART LINK]`,
      };
    }

    default:
      return {
        subject: "Your Seawolves seats",
        email: `Hi,

You left ${seats} in your cart. ${label}.

Finish up here: [CART LINK]

Seattle Seawolves`,
        sms: `Your Seawolves seats are still held. Finish up: [CART LINK]`,
      };
  }
}
