import type { CartFacts } from "./schema.ts";
import { getOffer, upgradeTarget } from "./catalog.ts";
import { milestone, MILESTONE_SEATS } from "./policy.ts";

/**
 * What the marketer actually sends.
 *
 * There is no CRM here and there won't be one this sprint, so the real output
 * of an approval isn't a database write — it's text a person can paste into
 * their email client on Monday morning. This file is that text.
 *
 * Deliberately templated rather than generated by a fourth agent. Copy is the
 * one artifact a fan reads word for word, which makes it the place where a
 * hallucination does the most damage and buys the least: a model might write a
 * warmer sentence, and it might also promise a fixture that isn't scheduled or
 * a discount we don't offer. Templates can't. The marketer edits before sending
 * anyway, so the upside of generating it is small and the downside isn't.
 *
 * The tone rule throughout: say the thing, don't perform enthusiasm. A club
 * this size is talking to people who may well have met the players.
 */

export interface SendCopy {
  subject: string;
  email: string;
  sms: string;
}

function seatPhrase(cart: CartFacts): string {
  return `${cart.seats} seat${cart.seats === 1 ? "" : "s"} in the ${cart.section}`;
}

/**
 * The milestone line, when this cart earns one.
 *
 * Two things are deliberately NOT said here: how many tickets it took, and that
 * there's a rule at all.
 *
 * Publishing "every 15 tickets earns an upgrade" turns a thank-you into a
 * contract. It sets an expectation the club then has to honour forever, it
 * invites someone to work out that a cheap extra seat is worth a $74 voucher,
 * and it makes the reward feel owed rather than given. Unannounced, it does the
 * job it was built for — the loyal fan who correctly gets no discount still
 * hears something worth reading — without any of that.
 *
 * So the fan is told what they've earned. Not how, and not what comes next.
 */
function milestoneLine(cart: CartFacts): string {
  const m = milestone(cart);
  if (!m) return "";
  const seats = `${MILESTONE_SEATS} seats`;

  if (m.reward.kind === "priced_down") {
    return `\n\nOne more thing. You've been with us a while, and you're already in the best seats in the ground — so there's nowhere left to move you. Instead, next time you book, ${seats} in the ${cart.section} are yours at ${m.reward.section} prices. It'll be waiting on your account.`;
  }
  return `\n\nOne more thing. Finish this order and you've earned ${seats} in the ${m.reward.section} at ${cart.section} prices, whenever you next book. It'll be waiting on your account.`;
}

export function buildCopy(cart: CartFacts, offerId: string): SendCopy {
  const offer = getOffer(offerId);
  const seats = seatPhrase(cart);
  const label = offer?.label ?? "your cart";

  switch (offerId) {
    case "reminder_only":
      return {
        subject: !milestone(cart)
          ? "Your Seawolves seats are still held"
          : "Your seats are held — and there's something on your account",
        email: `Hi,

You left ${seats} in your cart. They're still there if you want them — nothing has been taken off the board yet.${milestoneLine(cart)}

Finish up here: [CART LINK]

See you at the match,
Seattle Seawolves`,
        sms: (() => {
          const m = milestone(cart);
          if (!m) return `Your ${seats} for the Seawolves are still held. Finish up: [CART LINK]`;
          return m.reward.kind === "upgrade"
            ? `Your ${seats} are still held — and finishing up earns you ${MILESTONE_SEATS} ${m.reward.section} seats at ${cart.section} prices next time. [CART LINK]`
            : `Your ${seats} are still held — and finishing up earns you ${MILESTONE_SEATS} ${cart.section} seats at ${m.reward.section} prices next time. [CART LINK]`;
        })(),
      };

    case "discount_10":
    case "discount_15": {
      const pct = offerId === "discount_15" ? "15%" : "10%";
      const saved = offer ? offer.cashCost(cart).toFixed(2) : "0.00";
      return {
        subject: `${pct} off your Seawolves seats`,
        email: `Hi,

You left ${seats} in your cart. Here's ${pct} off — $${saved} — if you'd like to come and see us.

Finish up here: [CART LINK]

See you at the match,
Seattle Seawolves`,
        sms: `${pct} off your ${seats} for the Seawolves — $${saved} off. Finish up: [CART LINK]`,
      };
    }

    default:
      return {
        subject: "Your Seawolves seats",
        email: `Hi,

You left ${seats} in your cart. ${label}.

Finish up here: [CART LINK]

Seattle Seawolves`,
        sms: `Your Seawolves seats are still held. Finish up: [CART LINK]`,
      };
  }
}
