import type { CartFacts } from "./schema.ts";
import { getOffer, upgradeTarget } from "./catalog.ts";
import { milestone, TICKETS_PER_UPGRADE } from "./policy.ts";

/**
 * What the marketer actually sends.
 *
 * There is no CRM here and there won't be one this sprint, so the real output
 * of an approval isn't a database write — it's text a person can paste into
 * their email client on Monday morning. This file is that text.
 *
 * Deliberately templated rather than generated by a fourth agent. Copy is the
 * one artifact a fan reads word for word, which makes it the place where a
 * hallucination does the most damage and buys the least: a model might write a
 * warmer sentence, and it might also promise a fixture that isn't scheduled or
 * a discount we don't offer. Templates can't. The marketer edits before sending
 * anyway, so the upside of generating it is small and the downside isn't.
 *
 * The tone rule throughout: say the thing, don't perform enthusiasm. A club
 * this size is talking to people who may well have met the players.
 */

export interface SendCopy {
  subject: string;
  email: string;
  sms: string;
}

function seatPhrase(cart: CartFacts): string {
  return `${cart.seats} seat${cart.seats === 1 ? "" : "s"} in the ${cart.section}`;
}

/**
 * The milestone line, when this cart earns one.
 *
 * Goes in every template rather than only the reminder, because a fan crossing
 * their 45th ticket should hear about it whatever else we're sending. It also
 * turns the one message a loyal fan gets from a nag into news, which is the
 * whole point of having it.
 */
function milestoneLine(cart: CartFacts): string {
  const m = milestone(cart);
  // Nothing to promise if they're already in the best seats in the ground.
  if (!m || !m.upgradeTo) return "";
  const party =
    cart.seats === 1 ? "you" : cart.seats === 2 ? "both of you" : `all ${cart.seats} of you`;
  return `\n\nAnd these take you to ${m.ticketsAfter} tickets with us. Every ${TICKETS_PER_UPGRADE} earns a free upgrade, so we'll move ${party} to the ${m.upgradeTo} for this match — same price, and you'll be sitting together.`;
}

export function buildCopy(cart: CartFacts, offerId: string): SendCopy {
  const offer = getOffer(offerId);
  const seats = seatPhrase(cart);
  const label = offer?.label ?? "your cart";

  switch (offerId) {
    case "reminder_only":
      return {
        subject: milestone(cart)?.upgradeTo
          ? "Your next seats earn you an upgrade"
          : "Your Seawolves seats are still held",
        email: `Hi,

You left ${seats} in your cart. They're still there if you want them — nothing has been taken off the board yet.${milestoneLine(cart)}

Finish up here: [CART LINK]

See you at the match,
Seattle Seawolves`,
        sms: milestone(cart)?.upgradeTo
          ? `Your ${seats} are still held — and they take you to ${milestone(cart)!.ticketsAfter} tickets, which moves the whole party up to the ${milestone(cart)!.upgradeTo}. Finish up: [CART LINK]`
          : `Your ${seats} for the Seawolves are still held. Finish up: [CART LINK]`,
      };

    case "fee_waiver": {
      const saved = offer ? offer.cashCost(cart).toFixed(2) : "0.00";
      return {
        subject: "We've taken the fees off your Seawolves seats",
        email: `Hi,

You left ${seats} in your cart. We've taken the service fees off — that's $${saved} — if you'd like to pick them back up.

Finish up here: [CART LINK]

See you at the match,
Seattle Seawolves`,
        sms: `Your Seawolves seats are still held and we've waived the $${saved} in fees. Finish up: [CART LINK]`,
      };
    }

    case "upgrade_one_tier": {
      const target = upgradeTarget(cart.section);
      return {
        subject: `We'd like to move you to the ${target}`,
        email: `Hi,

You left ${seats} in your cart. It's been a while since we've seen you, so we'd like to move you up to the ${target} at the price you already had.

Same cost, better view. Finish up here: [CART LINK]

See you at the match,
Seattle Seawolves`,
        sms: `We'd like to move your Seawolves seats up to the ${target} — same price. Finish up: [CART LINK]`,
      };
    }

    case "discount_10":
    case "discount_15": {
      const pct = offerId === "discount_15" ? "15%" : "10%";
      const saved = offer ? offer.cashCost(cart).toFixed(2) : "0.00";
      return {
        subject: `${pct} off your Seawolves seats`,
        email: `Hi,

You left ${seats} in your cart. Here's ${pct} off — $${saved} — if you'd like to come and see us.

Finish up here: [CART LINK]

See you at the match,
Seattle Seawolves`,
        sms: `${pct} off your ${seats} for the Seawolves — $${saved} off. Finish up: [CART LINK]`,
      };
    }

    default:
      return {
        subject: "Your Seawolves seats",
        email: `Hi,

You left ${seats} in your cart. ${label}.

Finish up here: [CART LINK]

Seattle Seawolves`,
        sms: `Your Seawolves seats are still held. Finish up: [CART LINK]`,
      };
  }
}
